# Generated by Django 5.2.17 on 2026-09-22 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Vista de página'), ('social_click', 'Click en red social'), ('contact_click', 'Click en contacto'), ('gallery_open', 'Apertura de galería'), ('cta_click', 'Click en CTA'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('suggestion_created', 'Sugerencia creada'), ('suggestion_updated', 'Sugerencia actualizada')], max_length=30)),
                ('page', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de analítica',
                'verbose_name_plural': 'Eventos de analítica',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'page', 'created_at'], name='analytics_a_event_t_35bf14_idx')],
            },
        ),
    ]
